##image: maven:3.5.4-jdk-8
image: maven_mysql:latest
#services:
#     - name: mysql:latest

variables:
      # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    # MYSQL_USER: test
    # MYSQL_PASSWORD: test
    # MYSQL_ROOT_PASSWORD: pie.j9Ivae7cohtha
    # MYSQL_DATABASE: ttschool
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true "


compile_test:
    script:
    #- apt-get update && apt-get -y upgrade && apt-get -y install mysql-client
    - find /var/lib/mysql/mysql -exec touch -c -a {} + && service mysql start
    - mysql -h localhost -u test -ptest < sql/ttschool.sql
    - mvn $MAVEN_CLI_OPTS clean compile test


    tags:
         - mysql
